tests/410-namespace-conflict4.t.1:3:1: error: x already exists
